GestionAssurance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('assurance_auto.urls', namespace='assurance_auto')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import AccountListView


app_name = "account"

urlpatterns = [
    path('user/add_user/', views.add_user_view, name='add_user'),
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),
    path('userListe/',views.userList,name = "userListe"),
    path('accounts/', AccountListView.as_view(), name='all_accounts'),
]

assurance_auto/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
from assurance_auto.views import ContratViewSet,ReglementViewSet


router = routers.DefaultRouter()
router.register(r'contrat', ContratViewSet)
router.register(r'reglement', ReglementViewSet)


app_name='assurance_auto'
urlpatterns=[
    path('', views.home_page,name='home_page'),
    path('dashboard/', views.Dashboard, name='dashboard'),
    path('add/proprietaire/', views.AddClient, name='addProprietaire'),
    path('client/', views.Clients, name='clients'),
    path('ListeClient/', views.ClientList, name='ListeClient'),
    path('client/<int:id>/edit',views.ClientUpdate, name='Edit_Client'),

    path('marque/',views.CreateMarque, name='AddMarque'),
    path('marque/List',views.MarqueList, name='MarqueListe'),
    path('<int:id>/edit',views.UpdateMarque, name='Edit_Marque'),

    path('model/',views.CreateModel, name='AddModel'),
    path('model/List',views.ModelListe, name='Model_Liste'),

    path('vehicule/',views.CreateVehicule, name='AddVehicule'),
    path('vehicule/List/',views.VehiculeListe, name='Vehicule_Liste'),
    path('vehicule/<int:id>/edit',views.VehiculeUpdate, name='Edit_Vehicule'),
    path('Vehicule/<int:id>/detail/',views.vehicule_detail, name='Detail_vehicule'),

    path('typeContrat/Assurance/',views.CreateContratType, name='TypeContrat_Assurance'),
    path('type_contrat/<int:id>/edit',views.ContratTypeUpdate, name='Edit_typeContrat'),
    path('vehicule/add',views.CreateContrat, name='AddContrat'),
    path('contrat/List/',views.ContratListe, name='Contrat_Liste'),
    path('contrat/<int:id>/edit',views.ContratUpdate, name='Edit_Contrat'),
    path('contrat/<int:id>/modif',views.ModifContrat, name='Modif_Contrat'),
    path('contrat/<int:id>/detail/',views.ContractDetail, name='Detail_contrat'),

    path('reglement/nouveau/', views.new_invoice, name='new_invoice'),
    path('nouveau/Reglement/',views.AddReglement, name='addReglement'),
    # path('nouveau/Reglement/',views.CreateReglement, name='addReglement'),
    path('reglement/<int:id>/edit/',views.UpdateReglement, name='Edit_Reglement'),
    path('reglement/<int:id>/edit/',views.UpdateReglement, name='Edit_Reglement'),
    path('reglement/<int:id>/modify/',views.ModifyReglement, name='Modify_Reglement'),
    path('reglement/<int:id>/detail/',views.detailReglement, name='DetailReglement'),
    path('reglement/<int:id>/pdf/', views.order_pdf, name='reglement_pdf'),


     path('nouvelle/Depense/',views.CreateDepenses, name='nouvelleDepense'),
     path('depense/<int:id>/details/',views.DepenseDetail, name='detail_Depense'),
     path('depense/<int:id>/modif',views.ModifDepense, name='Modif_Depense'),
    

    # Contrat assurance
    path('assurance/alerte/', views.notification, name='alerte_expiration'),
    path('assurance/<int:id>/carton/', views.Carton_assurance, name='carton_assurance'),



    path('', include(router.urls)),

]

assurance_auto/forms.py
from django import forms
from assurance_auto.models import ProprietaireVehicule,Reglement,\
Vehicule,Contrat,Marque_Vehicule,Model_Vehicule, TypeContrat, Depenses

from django.contrib.auth.models import User

class ProprietaireAddForm(forms.ModelForm):
    class Meta:
        model= ProprietaireVehicule
        fields=['CIN','nom','prenom','photo','adresse','telephone','email']
        # widgets={
        #     'CIN':forms.TextInput(attrs={'class':'input'}),
        # }

class DepenseAddForm(forms.ModelForm):
    class Meta:
        model=Depenses
        exclude=('code_depense','utilisateur',)

class MarqueAddForm(forms.ModelForm):
    class Meta:
        model=Marque_Vehicule
        fields='__all__'

class ModelAddForm(forms.ModelForm):
    class Meta:
        model=Model_Vehicule
        fields='__all__'

class VehiculeAddForm(forms.ModelForm):
    class Meta:
        model=Vehicule
        fields='__all__'

class ContratAddFrom(forms.ModelForm):
    class Meta:
        model=Contrat
        exclude=('utilisateur','nombre_de_mois','numero_de_contrat','remainingdays','blocked_date','unblocked_date','montant_regle', 'tca',)
        # fields=('Categorie_assurance','Proprietaire','Conducteur','periode_jours','montant_du_contrat','statut',)

class TypeContratAddForm(forms.ModelForm):
    class Meta:
        model=TypeContrat
        exclude=('utilisateur',)

class ReglementAddForm(forms.ModelForm):
    class Meta:
        model=Reglement
        exclude = ('utilisateur','remainAmount','code_reglement')
        # fields='__all__'
        widgets = {
               'mode_de_paiment': forms.RadioSelect()
           }

assurance_auto/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from .forms import ProprietaireAddForm, VehiculeAddForm, ModelAddForm,\
    MarqueAddForm,ContratAddFrom, ReglementAddForm, TypeContratAddForm,DepenseAddForm
from .models import ProprietaireVehicule, Vehicule, Contrat, \
    Model_Vehicule,Marque_Vehicule,Reglement, TypeContrat, Depenses
from django.shortcuts import get_object_or_404, redirect
# Importing the render_to_pdf function from the render.py file.
from .render import render_to_pdf
from django.contrib.auth.models import User
from datetime import datetime, timedelta,date
import datetime
from decimal import *
from itertools import chain
from django.contrib import messages
from django.urls import reverse
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Sum, Count

from celery import Celery
from celery.schedules import crontab
from django.contrib.admin.views.decorators import staff_member_required

from twilio.rest import Client
from django.conf import settings


from rest_framework import viewsets
from .serializers import ContratSerializer, ReglementSerializer
# def status_changeScheduler(request):
#     contractList = Contrat.objects.all()

#     return render(request, 'home.html')


@login_required(login_url='/account/login')
def home_page(request):

    return render(request,'home.html', {})

@login_required(login_url='/account/login')
def Dashboard(request):
    template = 'auto/dashboard.html'
    from_date = request.GET.get('datedebut')
    to_date = request.GET.get('datefin')

    year_from = request.GET.get('year')

    month_from = request.GET.get('month')

    ListReglement=Reglement.objects.all().order_by('date_reglement')

    # Daily income
    list_benefice=[]
    list_periode = []
    benefice_periodique = Reglement.objects.filter(date_reglement__range=(from_date, to_date))\
    .values('date_reglement').annotate(Total_benefice=Sum('montant_a_regler')).order_by('date_reglement')
    for dict_item in benefice_periodique:
        paymentPeriode=dict_item['date_reglement'].strftime("%d-%m-%Y")
        list_benefice.append(float(dict_item['Total_benefice']))
        list_periode.append(paymentPeriode)
    
    # Daily expenses
    daily_list_expense=[]
    daily_periode_expense = []
    daily_expense = Depenses.objects.filter(date_depense__range=(from_date, to_date))\
    .values('date_depense').annotate(Total_expense=Sum('montant')).order_by('date_depense')
    for dict_item in daily_expense:
        expensePeriode=dict_item['date_depense'].strftime("%d-%m-%Y")
        daily_list_expense.append(float(dict_item['Total_expense']))
        daily_periode_expense.append(expensePeriode)

    
    # Yearly income
    YearList=[]
    YearlyIncome=[]

    yearly_income = Reglement.objects\
    .values('date_reglement__year').annotate(Total_benefice=Sum('montant_a_regler'))\
    .order_by('-date_reglement__year')[:5]
    for dict_item in yearly_income:
        YearList.append(dict_item['date_reglement__year'])
        YearlyIncome.append(float(dict_item['Total_benefice']))
    # print(YearList, YearlyIncome)

    # Yearly expense
    listEpenseAnnuelle=[]
    depensePeriode=[]
    yearly_expense = Depenses.objects\
    .values('date_depense__year').annotate(Total_depense=Sum('montant'))\
    .order_by('-date_depense__year')[:5]
    for dict_item in yearly_expense:
        depensePeriode.append(dict_item['date_depense__year'])
        listEpenseAnnuelle.append(float(dict_item['Total_depense']))


    # Monthly reports

    # Monthly incomes
    monthly_income_list=[]
    MonthList=[]
    monthly_income = Reglement.objects\
    .values('date_reglement__month').annotate(Total_benefice=Sum('montant_a_regler'))\
    .order_by('-date_reglement__month')[:12]
    for dict_item in monthly_income:
        MonthList.append(dict_item['date_reglement__month'])
        monthly_income_list.append(float(dict_item['Total_benefice']))
    # print(YearList, YearlyIncome)

    # monthly expenses
    monthlyExpenseList=[]
    monthlyExpense=[]
    monthly_expense = Depenses.objects\
    .values('date_depense__month').annotate(Total_depense=Sum('montant'))\
    .order_by('-date_depense__month')[:12]
    for dict_item in monthly_expense:
        monthlyExpenseList.append(dict_item['date_depense__month'])
        monthlyExpense.append(float(dict_item['Total_depense']))
    expenseListe= Depenses.objects.all()
    context={
        'ListReglement':ListReglement,
        # Daily reports
            # Incomes
        'benefice':list_benefice,
        'list_periode':list_periode,
            # Expenses
        'list_daily_expense':daily_list_expense,
        'list_periode_expense':daily_periode_expense,
        
        # Monthly reports
            # Incomes
        'monthly_income_list':monthly_income_list,
        'MonthIncomeList':MonthList,
            # Expenses
        'monthlyExpenseList':monthlyExpenseList,
        'monthlyExpense':monthlyExpense,

        # Yearly reports
        'YearList':YearList,
        'YearlyIncome':YearlyIncome,
        'listEpenseAnnuelle':listEpenseAnnuelle,
        'depensePeriode':depensePeriode, 
        'expenseListe':expenseListe
    }
    return render(request, template, context)

# @login_required(login_url='/account/login')
# def ListeDepense(request):
#     expenseListe= Depenses.objects.all()
#     return render(request, 'auto/dashboard.html', 
#                     {'expenseListe':expenseListe})



@login_required(login_url='/account/login')
def Clients(request):
    clients = ProprietaireVehicule.objects.all()
    form =ProprietaireAddForm(request.POST or None, request.FILES)
    if form.is_valid():
        form.save()
        form=ProprietaireAddForm()
    else:
        ProprietaireAddForm()
    return render(request,'auto/clients.html',
                  {'form':form,
                   'client_list':clients})

@login_required(login_url='/account/login')
def AddClient(request):
    clients = ProprietaireVehicule.objects.all()
    if request.method=='POST':
        form = ProprietaireAddForm(request.POST or None, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('assurance_auto:ListeClient')
            # form = ProprietaireAddForm()
    else:
        form = ProprietaireAddForm()
    return render(request,
                    'auto/AddClients.html',
                    {'form': form})


@login_required(login_url='/account/login')
def ClientList(request):
    clients = ProprietaireVehicule.objects.all()
    return render(request,
                    'auto/ListeClients.html',
                    {
                      'listClient': clients})

@login_required(login_url='/account/login')
def ClientUpdate(request, id=None):
    context={}
    detail = get_object_or_404(ProprietaireVehicule, id=id)
    form = ProprietaireAddForm(request.POST or None, request.FILES, instance=detail)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        id = form.instance.id
        return redirect('assurance_auto:ListeClient')
    else:
        form = ProprietaireAddForm(instance=detail)
    context["form"] = form
    return render(request, 'auto/UpdateClient.html', context)



@login_required(login_url='/account/login')
def CreateMarque(request):
    MarqueList = Marque_Vehicule.objects.all()
    form = MarqueAddForm(request.POST or None,)
    if form.is_valid():
        form.save()
        form = MarqueAddForm()
    else:
        MarqueAddForm()
    return render(request, 'auto/AddMarque.html',
                  {'form': form,
                   'client_list': MarqueList})

@login_required(login_url='/account/login')
def MarqueList(request):
    form = MarqueAddForm(request.POST or None, )
    if form.is_valid():
        form.save()
        form = MarqueAddForm()
    else:
        MarqueAddForm()
    MarqueList = Marque_Vehicule.objects.all()
    return render(request,
                  'auto/MarqueListe.html',
                  {
                      'form': form,
                      'MarqueList':MarqueList})

@login_required(login_url='/account/login')
def UpdateMarque(request, id=None):
    detail = get_object_or_404(Marque_Vehicule, id=id)
    form = MarqueAddForm(request.POST or None, instance=detail)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        # id = form.instance.id
        # return redirect('hr:personnel_details', id=id)
        return redirect('hr:paymentList')
    else:
        form=MarqueAddForm(instance=detail)
    context = {
        "form": form,
        "title": "Update payment"
    }
    return render(request, 'auto/AddMarque.html', context)

@login_required(login_url='/account/login')
def CreateModel(request):
    ModelList = Model_Vehicule.objects.all()
    form = ModelAddForm(request.POST or None,)
    if form.is_valid():
        form.save()
        form = ModelAddForm()
    else:
        ModelAddForm()
    return render(request, 'auto/AddModel.html',
                  {'form': form,
                   'client_list': ModelList})

@login_required(login_url='/account/login')
def ModelListe(request):
    form = ModelAddForm(request.POST or None, )
    if form.is_valid():
        form.save()
        form = ModelAddForm()
    else:
        ModelAddForm()
    ModelList = Model_Vehicule.objects.all()
    return render(request,
                  'auto/ListeModels.html',
                  {
                      'form': form,
                      'ModelList':ModelList})

@login_required(login_url='/account/login')
def CreateVehicule(request):
    VehiculeList = Vehicule.objects.all().order_by('-created')
    if request.method=='POST':
        form = VehiculeAddForm(request.POST or None,)
        if form.is_valid():
            form.save()

assurance_auto/templates/auto/Contrat - Copie.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    NOUVEAU VEHICULE
{% endblock %}
{% load static %}
{% block content %}

    <div class="from">
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                    {{ form.categorie|as_crispy_field }}
                    {{ form.statut_assurance|as_crispy_field }}
                    {{ form.nombre_de_mois|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.vehicule|as_crispy_field }}
                    {{ form.sous_couvert|as_crispy_field }}
                </div>
            </div>
            <!-- <hr>
            <div style="background-color:lightslategrey" align="center"><strong>TYPE DE GARANTIE</strong> </div>
            <div class="row">

                <div class="col-2">
                    {{ form.responsability|as_crispy_field }}  
                </div>
                <div class="col-2">
                    {{ form.incendie_vehicule|as_crispy_field }}
                </div>
                <div class="col-2">
                   {{ form.vole_du_vehicule|as_crispy_field }} 
                </div>
                <div class="col-2">
                    {{ form.brise_de_glasses|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.dommages_Coallisions|as_crispy_field }}
                </div>
                <div class="col-2">
                    {{ form.defense_et_recours|as_crispy_field }}
                </div>
                
            </div> -->

            <hr>
            <div class="row">
                <div class="col-6">
                    <button type="submit" class="btn btn-primary btn-block btn-small">Enregistrer</button>
                    
                </div>
                <div class="col-6">
                    <a href="{% url 'assurance_auto:Contrat_Liste' %}" class="btn btn-warning btn-block btn-small">Annuler</a>
                </div>
                
            </div>
            <br>
            <i>(*): Information obligatoire. </i>
        </form>
    </div>
{% endblock content %}

assurance_auto/templates/auto/Contrat.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}
    NOUVEAU VEHICULE
{% endblock %}
{% load static %}
{% block content %}

    <div class="from">
        <form method="post" action="." enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
                <div class="col-6">
                    {{ form.categorie|as_crispy_field }}
                    {{ form.statut_assurance|as_crispy_field }}
                    {{ form.nombre_de_mois|as_crispy_field }}
                </div>
                <div class="col-6">
                    {{ form.type_contrat|as_crispy_field }}
                    {{ form.vehicule|as_crispy_field }}
                    {{ form.sous_couvert|as_crispy_field }}
                </div>
            </div>
            <hr>
            <div class="row">
                <div class="col-6">
                    <button type="submit" class="btn btn-primary btn-block btn-small">Enregistrer</button>
                    
                </div>
                <div class="col-6">
                    <a href="{% url 'assurance_auto:Contrat_Liste' %}" class="btn btn-warning btn-block btn-small">Annuler</a>
                </div>
                
            </div>
            <br>
            <i>(*): Information obligatoire. </i>
        </form>
    </div>
{% endblock content %}

assurance_auto/templates/auto/ContratDetails.html
{% extends 'base.html' %}
{% block content %}
    <h1>DETAIL DE CONTRAT</h1>
    <ul class="object-tools">
    </ul>
    <table class="table table-striped">
        <tr>
            <th>Garantie</th>
            <td>{{ contrats.type_contrat.garantie }}</td>
        </tr>
        <tr>
            <th>No contrat</th>
            <td>{{ contrats.numero_de_contrat }}</td>
        </tr>
        <tr>
            <th>Véhicule</th>
            <td>{{ contrats.vehicule }}</td>
        </tr>
        <tr>
            <th>Propriétaire</th>
            <td>{{ contrats.vehicule.proprietaire }}</td>
        </tr>
        <tr>
            <th>S/C</th>
            <td>{{ contrats.sous_couvert }} </td>
        </tr>
        <tr>
            <th>Montant du contrat</th>
            <td>{{ contrats.type_contrat.montant_du_contrat }} KMF</td>
        </tr>
        <tr>
            <th>TCA (4%): </th>
            <td>{{ contrats.tca }} KMF</td>
        </tr>
        <tr>
            <th>Contrat de:</th>
            <td>{{ contrats.type_contrat.duration }} jour(s)</td>
        </tr>
        <tr>
            <th>Jours restants</th>
            <td>{{ contrats.remainingdays }} jour(s)</td>
        </tr>
        <tr>
            <th>Date début</th>
            <td>{{ contrats.created }}</td>
        </tr>
        <tr>
            <th>Date fin du contrat</th>
            <td>{{ contrats.get_NbDays }} </td>
        </tr>
        <tr>
            <th>Actuelle statut</th>
            <td>{{ contrats.statut_assurance }}</td>
        </tr>
        
        <tr>
            <th>Nombre de place</th>
            <td>{{ contrats.vehicule.nb_place }} + CHAUFFEUR</td>
        </tr>
    </table>
    <a href="{% url 'assurance_auto:Contrat_Liste' %}" class="btn btn-info">Quitter</a
{% endblock content %}

assurance_auto/templates/auto/DepenseDetails.html
{% extends 'base.html' %}
{% load mathfilters %}
{% block content %}
        <h2><strong>DETAILS DEPENSE </strong></h2>
    <table class="table table-striped">
        <tr>
            <th>REF DEPENSE:</th> 
            <td>{{ depense.code_depense }}</td>
        </tr>
        <tr>
            <th>BENEFICIAIRE:</th>
            <td>{{ depense.beneficiaire }}</td>
        </tr>
        <tr>
            <th>OBJECTIF:</th>
            <td>{{ depense.objet }}</td>
        </tr>
        <tr>
            <th>MONTANT:</th>
            <td>{{ depense.montant }}</td>
        </tr>
        <tr>
            <th>DEPENSE REALISEE LE :</th>
            <td>{{ depense.date_depense }}</td>
        </tr>
        <tr>
            <th>COMMENTAIRE :</th>
            <td>{{ depense.commentaires }}</td>
        </tr>
        <tr>
            <th>ENREGISTRE PAR :</th>
            <td>{{ depense.utilisateur }}</td>
        </tr>
        <tr>
            <td>
                <a href="{% url 'assurance_auto:nouvelleDepense' %}"><button type="button" class="btn btn-warning"></span> Fermer</button></a>
            </td>
            
        </tr>
          
    </table>
    
{% endblock %}

assurance_auto/templates/auto/MarqueListe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-3">
        <ul class="list-group">
            <div id="btn_new">
                <a href="" data-toggle="modal" data-target="#exampleModal" class="btn btn-info" >Nouveau marque</a>
            </div>
            <!-- Add Department Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="list-group-item active">
                            <h5 class="modal-title" id="exampleModalLabel"><strong>Ajout des marques</strong></h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div> <!-- /modal header -->
                        <div class="modal-body">
                            <form action="" method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <br>
                                <button type="submit" class="btn btn-info">
                                    Enregistrer
                                </button>
                            </form>
                        </div>
                        <!-- /modal body -->
                    </div>
                </div>
            </div>
        </ul>
    </div> <!-- /sidebar -->
    <h3 align="center"><strong>LISTE DES MARQUES</strong></h3>

    <table class="table table-striped" id="productsTable">
        <thead>
            <tr>
                <th>N°</th>
                <th>Nom de la Marque</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for marque in MarqueList %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ marque.nom_marque }}</td>
                    <td><a href="{% url 'assurance_auto:Edit_Marque' marque.id %}">Modifier</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

assurance_auto/templates/auto/ModifDepense.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="modal-body">
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <br>
            <button type="submit" class="btn btn-info">
                Modifier
            </button>
        </form>
    </div>
{% endblock content %}

assurance_auto/templates/auto/VehiculeListe.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <!-- <div class="col-md-3">
        <ul class="list-group">
            <div id="btn_new">
                <a href="" data-toggle="modal" data-target="#exampleModal" class="btn btn-info" >Nouveau véhicule</a>
            </div>
            <br>
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="list-group-item active">
                            <h5 class="modal-title" id="exampleModalLabel"><strong>Ajout des véhicules</strong></h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <form action="" method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <br>
                                <button type="submit" class="btn btn-info">
                                    Enregistrer
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </ul>
    </div> -->
    <h3 align="center"><strong>ENREGISTEMENT DES VEHICULES</strong></h3>
    <div class="table-responsive" style="overflow-x:auto;">
        <table class="table table-striped" id="myTable" name="myTable">
            <thead>
                <tr>
                    <th>IMMATRICULATION</th>
                    <th>CARTE GRISE</th>
                    <th>MODEL</th>
                    <!-- <th>PUISSANCE</th> -->
                    <!-- <th>Nb PLACE</th> -->
                    <!-- <th>POIDS AUTORISE</th> -->
                    <th>PROPRIETAIRE</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for vehicule in VehiculeList %}
                    <tr>
                        <td>{{ vehicule.immatriculation }}</td>
                        <td>{{ vehicule.numero_carte_grise }}</td>
                        <td>{{ vehicule.model }}</td>
                        <!-- <td>{{ vehicule.puissance }}</td> -->
                        <!-- <td>{{ vehicule.nb_place }}</td> -->
                        <!-- <td>{{ vehicule.poids_autorise }}</td> -->
                        <td>{{ vehicule.proprietaire }}</td>
                        <!-- <td>{{ vehicule.largeur }}</td> -->
                        <td>
                            <a href="{% url 'assurance_auto:Edit_Vehicule' vehicule.id %}" class="btn btn-warning">Modifier</a>
                            <a href="{% url 'assurance_auto:Detail_vehicule' vehicule.id %}" class="btn btn-info">Détails</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <script>
        $(document).ready(function() {
        // Setup - add a text input to each footer cell
        $('#myTable thead tr').clone(true).appendTo('#myTable thead');
        $('#myTable thead tr:eq(1) th').each( function (i) {
            var title = $(this).text();
            $(this).html( '<input type="text" placeholder="'+title+'" />' );
            $('input', this ).on( 'keyup change', function () {
                if ( table.column(i).search() !== this.value ) {
                    table
                        .column(i)
                        .search( this.value )
                        .draw();
                }
            } );
        } );

        var table = $('#myTable').DataTable( {
            orderCellsTop: true,
            fixedHeader: true
            } );
        } );
    </script>
    <script type="text/javascript">
        function myFunction() {
        var input, filter, table, tr, td, i;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[1]; // for column two
                td1 = tr[i].getElementsByTagName("td")[2]; // for column three
                /* ADD columns here that you want you to filter to be used on */
            if (td) {
              if ( (td.innerHTML.toUpperCase().indexOf(filter) > -1) || (td1.innerHTML.toUpperCase().indexOf(filter) > -1) )  {
                tr[i].style.display = "";
              } else {
                tr[i].style.display = "none";
              }
            }
          }
        }
    </script>
{% endblock content %}