GestionAssurance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('assurance_auto.urls', namespace='assurance_auto')),
]
if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

account/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import AccountListView


app_name = "account"

urlpatterns = [
    path('user/add_user/', views.add_user_view, name='add_user'),
    path('register/',views.register,name = "register"),
    path('login/',views.loginUser,name = "login"),
    path('logout/',views.logoutUser,name = "logout"),
    path('userListe/',views.userList,name = "userListe"),
    path('accounts/', AccountListView.as_view(), name='all_accounts'),
]

assurance_auto/urls.py
from django.urls import path, include
from . import views
from rest_framework import routers
from assurance_auto.views import ContratViewSet,ReglementViewSet


router = routers.DefaultRouter()
router.register(r'contrat', ContratViewSet)
router.register(r'reglement', ReglementViewSet)


app_name='assurance_auto'
urlpatterns=[
    path('', views.home_page,name='home_page'),
    path('dashboard/', views.Dashboard, name='dashboard'),
    path('add/proprietaire/', views.AddClient, name='addProprietaire'),
    path('client/', views.Clients, name='clients'),
    path('ListeClient/', views.ClientList, name='ListeClient'),
    path('client/<int:id>/edit',views.ClientUpdate, name='Edit_Client'),

    path('marque/',views.CreateMarque, name='AddMarque'),
    path('marque/List',views.MarqueList, name='MarqueListe'),
    path('<int:id>/edit',views.UpdateMarque, name='Edit_Marque'),

    path('model/',views.CreateModel, name='AddModel'),
    path('model/List',views.ModelListe, name='Model_Liste'),

    path('vehicule/',views.CreateVehicule, name='AddVehicule'),
    path('vehicule/List/',views.VehiculeListe, name='Vehicule_Liste'),
    path('vehicule/<int:id>/edit',views.VehiculeUpdate, name='Edit_Vehicule'),
    path('Vehicule/<int:id>/detail/',views.vehicule_detail, name='Detail_vehicule'),

    path('typeContrat/Assurance/',views.CreateContratType, name='TypeContrat_Assurance'),
    path('type_contrat/<int:id>/edit',views.ContratTypeUpdate, name='Edit_typeContrat'),
    path('vehicule/add',views.CreateContrat, name='AddContrat'),
    path('contrat/List/',views.ContratListe, name='Contrat_Liste'),
    path('contrat/<int:id>/edit',views.ContratUpdate, name='Edit_Contrat'),
    path('contrat/<int:id>/modif',views.ModifContrat, name='Modif_Contrat'),
    path('contrat/<int:id>/detail/',views.ContractDetail, name='Detail_contrat'),

    path('reglement/nouveau/', views.new_invoice, name='new_invoice'),
    path('nouveau/Reglement/',views.AddReglement, name='addReglement'),
    # path('nouveau/Reglement/',views.CreateReglement, name='addReglement'),
    path('reglement/<int:id>/edit/',views.UpdateReglement, name='Edit_Reglement'),
    path('reglement/<int:id>/edit/',views.UpdateReglement, name='Edit_Reglement'),
    path('reglement/<int:id>/modify/',views.ModifyReglement, name='Modify_Reglement'),
    path('reglement/<int:id>/detail/',views.detailReglement, name='DetailReglement'),
    path('reglement/<int:id>/pdf/', views.order_pdf, name='reglement_pdf'),


     path('nouvelle/Depense/',views.CreateDepenses, name='nouvelleDepense'),
     path('depense/<int:id>/details/',views.DepenseDetail, name='detail_Depense'),
     path('depense/<int:id>/modif',views.ModifDepense, name='Modif_Depense'),
    

    # Contrat assurance
    path('assurance/alerte/', views.notification, name='alerte_expiration'),
    path('assurance/<int:id>/carton/', views.Carton_assurance, name='carton_assurance'),



    path('', include(router.urls)),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}KAMIL ASSURANCE {% endblock %}</title>

  <script src="https://kit.fontawesome.com/16475baae0.js" crossorigin="anonymous"></script>
  <!-- GOOGLE FONT -->
  <link href="https://fonts.googleapis.com/css?family=Nunito:400,700&display=swap" rel="stylesheet">
  
  <!-- BOOTSTRAP4 CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  
  <!-- CUSTOM CSS -->
  <link rel="stylesheet" href="{% static 'css/dashboard.css' %}">


  <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />

  <!-- Old CSS -->

    <!-- <link rel="stylesheet" href="{% static 'CSS_file/font-awesome-4.7.0/css/font-awesome.css' %}"> -->

    <link rel="stylesheet" href="{% static 'CSS_file/bootstrap-4.0.0/css/bootstrap.min.css' %}">
    <!-- Autres CSS -->
    <!-- <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet"> -->
    <!-- <link href="{% static 'css/style.min.css' %}" rel="stylesheet">    -->


  <!-- DataTable  --> 
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <link href="https://cdn.datatables.net/1.10.24/css/jquery.dataTables.min.css" rel="stylesheet" type="text/css" />
    <script src="https://cdn.datatables.net/1.10.24/js/jquery.dataTables.min.js"></script>

     <!-- CSS Charts -->
    <link rel="stylesheet" href="{% static 'Charts/styles/plugins/c3.css' %}">
    <link rel="stylesheet" href="{% static 'Charts/styles/plugins/perfect-scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'Charts/styles/plugins/waves.css' %}">

    <style type="text/css">
        .leftsideprod, .rightsideprod{
                height: 100vh;
                width: 80%;
            }

            .rightsideprod{
               width: 80%;
               margin-left: 0px;
                padding: 10px;
                /*background-color: #34ce57;*/

            }
            .leftsideprod{
                /*left: 0px;*/
                margin-left: 0px;
                padding: 10px;
                right: 0px;
                overflow: auto;
                width: 135%;

                /*background-color: lavender;*/

            }

            .leftside,.rightside{
                height: 114vh;
               /* width: 100%;
                background-color:#6a1b9a;*/
                position:absolute;

            }

            .leftside{
                /*left: 0px;*/
                margin-left: 0px;
                padding: 10px;
                right: 0px;
                overflow: auto;
                width: 142%;
                /*background-color: lavender;*/

            }
            .rightside{
                width: 142%;
                margin-left: 0px;
                padding: 10px;
                /*right: 0px;*/
                /*background-color:#36B9CC;*/
                /*background-color: lavender;*/
            }
            /*.col-sm-12{
                background-color:darkturquoise;

            }*/

            .container2 {
                margin-bottom: 50px;
                border: 1px solid rgba( 0,0,0, .4 );
                padding: 40px;
                border-radius: 6px;
                margin-left: 15%;
                margin-right:15%;
            }


            /*Hover CSS*/

            .card-body{
                text-decoration: none;
                &:hover{
                    transition: all 0.2s ease-out;
                    box-shadow: 0px 4px 8px rgba(38, 38, 38, 0.2);
                }   
            }

        .espacement{
            padding: 40px;
        }
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css">
  <!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script> -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body class="bg-light">
    <section id="dashboard">
        <div class="container-fluid">
            <div class="dashboard-container row">
                <!-- START SIDENAV -->
                <div class="col-12 col-sm-12 col-md-4 col-lg-2 sidenav">
                    <!-- <div class="logo"> -->
                        <!-- <img src="{% static 'images/MAC_BOUTIQUE.jpeg' %}" alt="" width="200px" height="100px"> -->
                        <h1><a href="/"  class="sn-link">KAMIL ASSURANCE</a></h1>
                    <!-- </div> -->
                    <div class="sn-group">
                        <a href="{% url 'assurance_auto:dashboard' %}" class="sn-link dash-home">
                            <i class="fas fa-tachometer-alt"></i>Tableau de bord
                        </a>
                    </div>

                    <div class="sn-group">
                        <h5>Marques & Véhicules</h5>
                        <nav>
                            <a class="sn-link dash-home" href="{% url 'assurance_auto:MarqueListe' %}">
                                <i class="fa fa-cubes"></i>Marques
                            </a>
                            <a class="sn-link dash-home" href="{% url 'assurance_auto:Model_Liste' %}">
                                <i class="fas fa-shipping-fast"></i>Modeles
                            </a>
                            <a class="sn-link dash-home" href="{% url 'assurance_auto:addProprietaire' %}">
                                <i class="fa fa-plus"></i>Nouveau client
                            </a>
                            <a class="sn-link dash-home" href="{% url 'assurance_auto:ListeClient' %}">
                                <i class="fa fa-users"></i>Liste clients
                            </a>
                            <a href="{% url 'assurance_auto:AddVehicule' %}" class="sn-link dash-home">
                                <i class="fa fa-car"></i>Nouveau Véhicule
                            </a>
                            <a href="{% url 'assurance_auto:Vehicule_Liste' %}" class="sn-link dash-home">
                                <i class="fa fa-list-alt"></i>Liste Véhicules
                            </a>
                        </nav>
                    </div>
                    <div class="sn-group dash-home">
                        <h5>Catégories & contrats assurances</h5>
                        <nav>
                            <a class="sn-link dash-home" href="{% url 'assurance_auto:TypeContrat_Assurance' %}">
                                <i class="fa fa-list"></i>Type de contrat assurance
                            </a>
                            <a class="sn-link dash-home" href="{% url 'assurance_auto:Contrat_Liste' %}">
                                <i class="fa fa-file-invoice"></i>Contrats
                            </a>

                            <a class="sn-link dash-home" href="{% url 'assurance_auto:alerte_expiration' %}">
                                <i class="fa fa-plus"></i>Lancement alerte
                            </a>
                            <a class="sn-link dash-home" href="{% url 'assurance_auto:addReglement' %}">
                                <i class="fas fa-coins"></i>Réglements
                            </a>
                            <a href="{% url 'assurance_auto:nouvelleDepense' %}" class="sn-link dash-home">
                               <i class="fa fa-plus"></i>Dépenses
                            </a>

                            <a href="" class="sn-link dash-home">
                               <i class="fa fa-chart-line"></i>Statistiques
                            </a>
                        </nav>
                    </div>
                    
                    <div class="sn-group">
                        <h5></h5>
                        <nav>
                           <!--  <a class="sn-link dash-home" href="">
                                <i class="fa fa-bar-chart" aria-hidden="true"></i>Article les plus vendus
                            </a>

                            <a href="" class="sn-link dash-home">
                               <i class="fa fa-chart-line"></i>Articles plus bénéfiques
                            </a>
                            <a href="" class="sn-link dash-home">
                               <i class="fa fa-wallet"></i>Solde par utilisateur
                            </a> -->
                        </nav>
                    </div>
                </div>
                    <!-- END OF SIDENAV -->
                {% block dashboard-body %}

                {% endblock dashboard-body %}
                <!-- START DASHBOARD BODY -->
                <div class="col-12 col-sm-12 col-md-8 col-lg-10 px-0 dashbody">
                    <!-- NAVIGATION TOP -->
                    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow py-3 px-5">
                        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"            aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>
                        </button>
                        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                            <h2> KAMIL ASSURANCE</h2>
                            <div class="navbar-nav ml-auto">
 
                                <li class="nav-item dropdown">

                                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                                    aria-expanded="false" style="color:black;"><i class="fa fa-cog" aria-hidden="true"></i>Paramétres</a>
                                    <div class="dropdown-menu">
                                        {% if request.user.is_authenticated %}
                                            <a class="dropdown-item" href="{% url 'account:logout' %}">
                                            Déconnecter {{ user.username }}
                                            </a>
                                        {% else %}
                                        <a class="dropdown-item" href="">Se connecter</a>
                                        {% endif %}
                                        <a class="dropdown-item" href="{% url 'account:all_accounts' %}" class="sn-link dash-home">Nouvel utilisateur
                                        </a>

                                        <a class="dropdown-item" href="" class="sn-link dash-home">Paramètres
                                        </a>

                                    </div>
                                </li>
                            </div>
                        </div>
                    </nav>
                     <div class="mt-5 pt-4">
                                {% if messages %}
                                    {% for message in messages %}
                                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                            {{ message }}
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                    {% endfor %}
                                {% endif %}
                            </div>
                    <div id="dash-body-inner" class="container-fluid p-5">
                        {% block content %}
                           
                        {% endblock %}
                    </div>
               </div>
                    <!-- END NAV TOP -->
                </div>

            <!-- END DASHBOARD BODY -->
            </div> <!-- dashboard container fluid -->
        </div>
    </section>
    <!-- <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script> -->


    <!-- jQuery -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fontawesome-iconpicker/3.2.0/js/fontawesome-iconpicker.min.js" integrity="sha512-7dlzSK4Ulfm85ypS8/ya0xLf3NpXiML3s6HTLu4qDq7WiJWtLLyrXb9putdP3/1umwTmzIvhuu9EW7gHYSVtCQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>
    <script src='https://kit.fontawesome.com/a076d05399.js'></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

templates/baseOld.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Système de Gestion des Assurance </title>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <style>
            
        </style>

        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'font_awesome/css/font-awesome.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'jqueryui/jquery-ui.min.css' %}">
        <!-- <link rel="stylesheet" type="text/css" href="{% static 'plugins/datatables/jquery.dataTables.min.css' %}"> -->
        <link rel="stylesheet" type="text/css" href="{% static 'plugins/fullcalendar/fullcalendar.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/datepicker.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

         <!-- DataTable css link -->
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css">

        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.4/css/jquery.dataTables.css">
  
        <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.4/js/jquery.dataTables.js"></script>




        <script src="https://nightly.datatables.net/js/jquery.dataTables.js"></script>

        <style>

            .btn {
                background-color: DodgerBlue;
                border: none;
                color: white;
                padding: 14px 28px;
                font-size: 22px;
                cursor: pointer;
                margin: 20px 20px;
                width: 250px;
                height: 200px;
            }

            /* Darker background on mouse-over */
            .btn:hover {
              background-color: RoyalBlue;
            }




            fieldset{
                width: 600px;
                padding: 5px;
            }
            legend{
                font-size: 20px;
            }
            label {
                font-weight: bold;
            }

            #myInput {
                {#background-image: url('/css/searchicon.png');#}
                background-position: 10px 10px;
                background-repeat: no-repeat;
                width: 50%;
                font-size: 16px;
                padding: 12px 20px 12px 40px;
                border: 1px solid #ddd;
                margin-bottom: 12px;
            }
            {#thead input {#}
            {#    width: 100%;#}
            {#}

            thead input {
                width: 100%;
                padding: 3px;
                box-sizing: border-box;
            }
        </style>

    </head>
    <body>
        <!-- {% include 'navbar.html' %} -->

        <nav class="navbar navbar-toggleable-lg" style="box-shadow: 0 0px 0px 0 rgba(0, 0, 0, 0.2), 0 2px 20px 0 rgba(0, 0, 0, 0.19)">
            <a class="navbar-brand" href="/">SGA</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="nav navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href=""><i class="fa fa-list-alt" aria-hidden="true"></i> Tableau de bord</a>
                    </li>
                    <li class="nav-item" id="navBrand">
                        <a class="nav-link" href="{% url 'assurance_auto:ListeClient' %}"><i class="fa fa-gamepad" aria-hidden="true"></i></i> Clients</a>
                    </li>
        {#            <li class="nav-item" id="navBrand">#}
        {#                <a class="nav-link" href=""><i class="fa fa-envira" aria-hidden="true"></i> Vehicules</a>#}
        {#            </li>#}

                    <li class="nav-item dropdown" id="navBrand">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          <i class="fa fa-envira" aria-hidden="true"></i>Véhicules
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
        {#                    <a class="dropdown-item" href="{% url 'assurance_auto:AddVehicule' %}">Ajouter un vehicule</a>#}
                            <a class="dropdown-item" href="{% url 'assurance_auto:Vehicule_Liste' %}">Liste des véhicules</a>
        {#                    <a class="dropdown-item" href="{% url 'assurance_auto:AddMarque' %}">Ajouter une marque</a>#}
                            <a class="dropdown-item" href="{% url 'assurance_auto:MarqueListe' %}">Liste des marques</a>
        {#                    <a class="dropdown-item" href="{% url 'assurance_auto:AddModel' %}">Ajouter un model</a>#}
                            <a class="dropdown-item" href="{% url 'assurance_auto:Model_Liste' %}">Liste des models</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-list" aria-hidden="true"></i> Paramettrage assurance
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                          <a class="dropdown-item" href="{% url 'assurance_auto:Category_Assurance' %}">Catégorie assurance</a>
                          <a class="dropdown-item" href="{% url 'assurance_auto:Contrat_Liste' %}">Liste des contrats</a>
        {#                  <a class="dropdown-item" href="{% url 'assurance_auto:new_invoice' %}">Nouveau reglement</a>#}
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <i class="fa fa-cubes" aria-hidden="true"></i></i> Réglement</a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'assurance_auto:addReglement' %}">Nouveau reglement</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href=""><i class="fa fa-line-chart" aria-hidden="true"></i></i> Rapport</a>
                    </li>
                </ul>
                {% if user.is_authenticated %}
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                   <i class="fa fa-user" aria-hidden="true"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-menu-right">
                                <div class="dropdown-item" style="color: cornflowerblue">{{ user|capfirst }}</div>
                                <a class="dropdown-item" href="#">Settings</a>
                                <a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a>
            {#                    <div class="dropdown-divider"></div>#}
            {#                    <a class="dropdown-item" href="#">Something else here</a>#}
                            </ul>
                        </li>
                    </ul>
                {% endif %}

            </div>
        </nav>


        {% if messages %}
            <div class="row">
                <!-- <div class="col-sm-6 col-sm-offset-3"> -->
                    {% for message in messages %}
                        <div class="{{ message.tags }}">
                            <h2 align="center">{{ message }}</h2>
                        </div>
                    {% endfor %}
                <!-- </div> -->

            </div>
        {% endif %}

        <div align="center">
            <br>
            <h5>VEHICULE, MARQUES, MODELS & CLIENTS</h5>
            <hr>
            <button class="btn"><i class='fa fa-cubes'></i> MARQUES</button>
            <button class="btn"><i class='fa fa-object-ungroup'></i> MODELS</button>
            <button class="btn"><i class='fa fa-car'></i> VEHICULES</button>
            <button class="btn"><i class='fa fa-users'></i> CLIENTS</button>
            <br>
            <br>
            <h5>CATEGORIES ASSURANCE, CONTRAT, ASSURANCE, & PAIMENT</h5>
            <hr>
            <button class="btn"><i class="fa fa-list" aria-hidden="true"></i>   CATEGRORIE</button>
            <button class="btn"><i class="fa fa-umbrella"></i> ASSURANCE</button>
            <button class="btn"><a class="nav-link" href="{% url 'assurance_auto:addReglement' %}"><i class="fa fa-money"></i> Réglement</a></button>
            <button class="btn"><i class="fa fa-line-chart" aria-hidden="true"></i> Rapport</button>
        </div>

        {% block content %} {% endblock %}
        {% block list %} {% endblock %}
    </body>
    <script src="{% static 'jquery/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'jqueryui/jquery-ui.min.js' %}"></script>
    <!-- <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script> -->
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'plugins/fullcalendar/moment.min.js' %}"></script>
    <script src="{% static 'plugins/fullcalendar/fullcalendar.min.js' %}"></script>
    <script src="{% static 'plugins/datepick/jquery.datepick.js' %}"></script>

    {% block script %}
        
    {% endblock %}


    <!-- Jquery dataTable -->
  <!-- <script type="text/javascript" src="https://code.jquery.com/jquery-3.5.1.js"></script> -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js"></script>
</html>

templates/navbar.html
 

{% block content %} 


{% endblock %}